---
- name: Create Directory
  hosts: your_host_or_group
  become: yes  # If creating the directory requires elevated privileges

  tasks:
    - name: Create Directory
      file:
        path: /path/to/new_directory  # Specify the path of the directory you want to create
        state: directory  # Indicates that it should be a directory
        mode: '0755'
